IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = N'dbo' AND TABLE_NAME = N'AggSalesDaily')
BEGIN
  CREATE TABLE dbo.AggSalesDaily(
    DateId INT NOT NULL
   ,StoreId SMALLINT NOT NULL
   ,ProductId VARCHAR(20) NOT NULL
   ,AggNetSales NUMERIC(20,2) NOT NULL
   ,AggSalesUnits INT NOT NULL
   ,CONSTRAINT PK_AggSalesDaily PRIMARY KEY CLUSTERED (DateId, StoreId, ProductId)
  );
END;
